version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: defects_user
      POSTGRES_PASSWORD: defects_pass
      POSTGRES_DB: defects_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=postgresql://defects_user:defects_pass@db:5432/defects_db
      - SECRET_KEY=replace-with-secure-key
    ports:
      - "9000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_URL=http://localhost:9000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
